zn.define([
    './AuctionSession',
    './Coupon',
    './Merchant',
    './MerchantUser',
    './Message',
    './Order',
    './OrderDetail',
    './Product',
    './ProductBids',
    './ProductType',
    './User',
    './UserAddress',
    './UserCollection',
    './UserRemind',
    './UserDeposit'
]);
