#!/usr/bin/env node

'use strict';
var zn = require('../src/zn.core.minx');
zn.define([
    'net',
    'io',
    'node:path',
    'node:child_process',
    'node:os',
    'node:fs'
], function (net, io, path, child_process, os, fs) {
    var argv = process.argv;
    //var execPath = argv[1].split(zn.SLASH).pop();
    var _argv = {};
    argv = argv.slice(2);

    zn.each(argv, function (value){
        var _temps = value.split(':'),
            _value = _temps[1];
        if(_value===undefined){
            _value = true;
        }
        _argv[_temps[0]] = _value;
    });

    var _host = os.platform() === 'darwin'?'127.0.0.1':'0.0.0.0';
    if(!_argv.debug){
        var os = require('os');
        zn.each(os.networkInterfaces(), function (en){
            zn.each(en, function (item){
                if(item.family=='IPv4'&&!item.internal){
                    _host = item.address;
                }
            })
        });
    }

    var _serverConfig = {
        host: '0.0.0.0',
        port: _argv.port || 8080,
        catalog: '/',
        onLoaded: function (){
            zn.info('You can press [ control + c ] to stop current zeanium server.');
        }
    };
    var _config = _argv.config || 'zn.server.config.js';
    var _configPath = process.cwd() + zn.SLASH + _config;

    if(fs.existsSync(_configPath)){
        zn.load(_configPath, function (data){
            var _config = zn.overwrite(data, _serverConfig);
            console.log('config: ', _config);
            net.http.HttpServer.createServer(_config);
        });
    }else {
        console.log('config: ', _serverConfig);
        net.http.HttpServer.createServer(_serverConfig);
    }

}).exec();
