#!/usr/bin/env node

'use strict';
var zn = require('../src/zn.core.minx');
zn.define([
    'net',
    'io',
    'node:path',
    'node:child_process',
    'node:os',
    'node:fs'
], function (net, io, path, child_process, os, fs) {
    var argv = process.argv;
    //var execPath = argv[1].split(zn.SLASH).pop();
    var _argv = {};
    argv = argv.slice(2);

    zn.each(argv, function (value){
        var _temps = value.split(':');
        _argv[_temps[0]] = _temps[1];
    });

    var _host = os.platform() === 'darwin'?'127.0.0.1':'0.0.0.0';
    var _configPath = process.cwd() + zn.SLASH + 'zn.server.config.js';


    var os = require('os');
    zn.each(os.networkInterfaces(), function (en){
        zn.each(en, function (item){
            if(item.family=='IPv4'&&!item.internal){
                _host = item.address;
            }
        })
    });

    var _serverConfig = {
        host: _host || '0.0.0.0',
        port: _argv.port || 8080,
        debug: false,
        mode: 'view',
        catalog: '/webapps/',
        onLoaded: function (){
            zn.info('You can press [ control + c ] to stop current zeanium server.');
        }
    };

    net.http.HttpServer.createServer(_serverConfig);

}).exec();
